"""initial schema

Revision ID: 0fe52f00493f
Revises: 
Create Date: 2025-12-30 19:40:39.009031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe52f00493f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_bookmakers_key'), 'bookmakers', ['key'], unique=True)
    op.create_table('sports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sports_key'), 'sports', ['key'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_key'), 'teams', ['key'], unique=False)
    op.create_index(op.f('ix_teams_sport_id'), 'teams', ['sport_id'], unique=False)
    op.create_index('ix_teams_sport_key', 'teams', ['sport_id', 'key'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index('ix_games_commence_time', 'games', ['commence_time'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index('ix_games_sport_commence', 'games', ['sport_id', 'commence_time'], unique=False)
    op.create_index(op.f('ix_games_sport_id'), 'games', ['sport_id'], unique=False)
    op.create_table('closing_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closing_lines_bookmaker_id'), 'closing_lines', ['bookmaker_id'], unique=False)
    op.create_index(op.f('ix_closing_lines_closed_at'), 'closing_lines', ['closed_at'], unique=False)
    op.create_index('ix_closing_lines_game', 'closing_lines', ['game_id'], unique=False)
    op.create_index(op.f('ix_closing_lines_game_id'), 'closing_lines', ['game_id'], unique=False)
    op.create_index(op.f('ix_closing_lines_market_type'), 'closing_lines', ['market_type'], unique=False)
    op.create_index('ix_closing_lines_unique', 'closing_lines', ['game_id', 'bookmaker_id', 'market_type'], unique=True)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_bookmaker_id'), 'odds_snapshots', ['bookmaker_id'], unique=False)
    op.create_index('ix_odds_snapshots_bookmaker_timestamp', 'odds_snapshots', ['bookmaker_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_game_id'), 'odds_snapshots', ['game_id'], unique=False)
    op.create_index('ix_odds_snapshots_game_market', 'odds_snapshots', ['game_id', 'market_type'], unique=False)
    op.create_index('ix_odds_snapshots_game_timestamp', 'odds_snapshots', ['game_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_market_type'), 'odds_snapshots', ['market_type'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_timestamp'), 'odds_snapshots', ['timestamp'], unique=False)
    op.create_index('ix_odds_snapshots_unique_snapshot', 'odds_snapshots', ['game_id', 'bookmaker_id', 'market_type', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_odds_snapshots_unique_snapshot', table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_timestamp'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_market_type'), table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_game_timestamp', table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_game_market', table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_game_id'), table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_bookmaker_timestamp', table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_bookmaker_id'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('ix_closing_lines_unique', table_name='closing_lines')
    op.drop_index(op.f('ix_closing_lines_market_type'), table_name='closing_lines')
    op.drop_index(op.f('ix_closing_lines_game_id'), table_name='closing_lines')
    op.drop_index('ix_closing_lines_game', table_name='closing_lines')
    op.drop_index(op.f('ix_closing_lines_closed_at'), table_name='closing_lines')
    op.drop_index(op.f('ix_closing_lines_bookmaker_id'), table_name='closing_lines')
    op.drop_table('closing_lines')
    op.drop_index(op.f('ix_games_sport_id'), table_name='games')
    op.drop_index('ix_games_sport_commence', table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index('ix_games_commence_time', table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    op.drop_index('ix_teams_sport_key', table_name='teams')
    op.drop_index(op.f('ix_teams_sport_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_key'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sports_key'), table_name='sports')
    op.drop_table('sports')
    op.drop_index(op.f('ix_bookmakers_key'), table_name='bookmakers')
    op.drop_table('bookmakers')
    # ### end Alembic commands ###
