"""add_user_bets_table

Revision ID: 9b8158e72dbf
Revises: f1104e42283c
Create Date: 2026-01-24 15:26:15.532222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8158e72dbf'
down_revision: Union[str, Sequence[str], None] = 'f1104e42283c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('game_description', sa.String(length=200), nullable=False),
    sa.Column('game_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('bet_description', sa.String(length=100), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('closing_odds', sa.Integer(), nullable=True),
    sa.Column('clv_percentage', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_bets_game_date', 'user_bets', ['game_date'], unique=False)
    op.create_index('ix_user_bets_result', 'user_bets', ['result'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_bets_result', table_name='user_bets')
    op.drop_index('ix_user_bets_game_date', table_name='user_bets')
    op.drop_table('user_bets')
    # ### end Alembic commands ###
