"""add point_line to best_ev_picks

Revision ID: ae018c662ca2
Revises: 1e27b7dea27a
Create Date: 2026-04-20 13:48:30.119646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae018c662ca2'
down_revision: Union[str, Sequence[str], None] = '1e27b7dea27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('best_ev_picks', sa.Column('point_line', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('best_ev_picks', 'point_line')
    # ### end Alembic commands ###
