"""add point_line to opportunity_performance

Revision ID: f1104e42283c
Revises: 8db8fc98d1bd
Create Date: 2026-01-18 01:52:59.954215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1104e42283c'
down_revision: Union[str, Sequence[str], None] = '8db8fc98d1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_performance', sa.Column('point_line', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_performance', 'point_line')
    # ### end Alembic commands ###
