"""Add profit tracking to daily reports

Revision ID: fb633588cc6d
Revises: fc914c918263
Create Date: 2026-01-10 23:48:27.275053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb633588cc6d'
down_revision: Union[str, Sequence[str], None] = 'fc914c918263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_clv_reports', sa.Column('settled_count', sa.Integer(), nullable=True))
    op.add_column('daily_clv_reports', sa.Column('win_count', sa.Integer(), nullable=True))
    op.add_column('daily_clv_reports', sa.Column('loss_count', sa.Integer(), nullable=True))
    op.add_column('daily_clv_reports', sa.Column('push_count', sa.Integer(), nullable=True))
    op.add_column('daily_clv_reports', sa.Column('hypothetical_profit', sa.Float(), nullable=True))
    op.add_column('daily_clv_reports', sa.Column('win_rate', sa.Float(), nullable=True))
    op.add_column('daily_clv_reports', sa.Column('roi', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_clv_reports', 'roi')
    op.drop_column('daily_clv_reports', 'win_rate')
    op.drop_column('daily_clv_reports', 'hypothetical_profit')
    op.drop_column('daily_clv_reports', 'push_count')
    op.drop_column('daily_clv_reports', 'loss_count')
    op.drop_column('daily_clv_reports', 'win_count')
    op.drop_column('daily_clv_reports', 'settled_count')
    # ### end Alembic commands ###
