"""Add betting outcomes and performance tracking

Revision ID: fc914c918263
Revises: 852e3163ab49
Create Date: 2026-01-10 23:42:26.579100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc914c918263'
down_revision: Union[str, Sequence[str], None] = '852e3163ab49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betting_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=100), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('point_differential', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_index('ix_betting_outcomes_game_id', 'betting_outcomes', ['game_id'], unique=False)
    op.create_table('opportunity_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('outcome_name', sa.String(length=100), nullable=False),
    sa.Column('entry_odds', sa.Float(), nullable=False),
    sa.Column('closing_odds', sa.Float(), nullable=False),
    sa.Column('clv_percentage', sa.Float(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['daily_clv_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunity_performance_game_id', 'opportunity_performance', ['game_id'], unique=False)
    op.create_index('ix_opportunity_performance_report_id', 'opportunity_performance', ['report_id'], unique=False)
    op.create_index('ix_opportunity_performance_result', 'opportunity_performance', ['result'], unique=False)
    op.drop_index(op.f('ix_daily_clv_reports_date'), table_name='daily_clv_reports')
    op.create_index('ix_daily_clv_reports_date', 'daily_clv_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_daily_clv_reports_report_date'), 'daily_clv_reports', ['report_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_clv_reports_report_date'), table_name='daily_clv_reports')
    op.drop_index('ix_daily_clv_reports_date', table_name='daily_clv_reports')
    op.create_index(op.f('ix_daily_clv_reports_date'), 'daily_clv_reports', ['report_date'], unique=True)
    op.drop_index('ix_opportunity_performance_result', table_name='opportunity_performance')
    op.drop_index('ix_opportunity_performance_report_id', table_name='opportunity_performance')
    op.drop_index('ix_opportunity_performance_game_id', table_name='opportunity_performance')
    op.drop_table('opportunity_performance')
    op.drop_index('ix_betting_outcomes_game_id', table_name='betting_outcomes')
    op.drop_table('betting_outcomes')
    # ### end Alembic commands ###
